/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 8
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 66
#define ALIAS_COUNT 0
#define TOKEN_COUNT 60
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_module = 2,
  anon_sym_pub = 3,
  anon_sym_import = 4,
  anon_sym_imports = 5,
  anon_sym_as = 6,
  anon_sym_apply = 7,
  anon_sym_return = 8,
  anon_sym_end = 9,
  anon_sym_if = 10,
  anon_sym_elif = 11,
  anon_sym_else = 12,
  anon_sym_while = 13,
  anon_sym_for = 14,
  anon_sym_in = 15,
  anon_sym_of = 16,
  anon_sym_by = 17,
  anon_sym_repeat = 18,
  anon_sym_times = 19,
  anon_sym_break = 20,
  anon_sym_continue = 21,
  anon_sym_match = 22,
  anon_sym_case = 23,
  anon_sym_loop = 24,
  anon_sym_struct = 25,
  anon_sym_enum = 26,
  anon_sym_alias = 27,
  anon_sym_do = 28,
  anon_sym_and = 29,
  anon_sym_or = 30,
  anon_sym_not = 31,
  anon_sym_using = 32,
  anon_sym_try = 33,
  anon_sym_const = 34,
  anon_sym_var = 35,
  anon_sym_int = 36,
  anon_sym_float = 37,
  anon_sym_bool = 38,
  anon_sym_string = 39,
  anon_sym_bytes = 40,
  anon_sym_void = 41,
  anon_sym_decimal = 42,
  anon_sym_list = 43,
  anon_sym_map = 44,
  anon_sym_optional = 45,
  anon_sym_result = 46,
  anon_sym_range = 47,
  anon_sym_true = 48,
  anon_sym_false = 49,
  anon_sym_none = 50,
  anon_sym_success = 51,
  anon_sym_error = 52,
  anon_sym_some = 53,
  sym_number = 54,
  sym_string = 55,
  sym_operator = 56,
  sym_punctuation = 57,
  sym_block_comment = 58,
  sym_line_comment = 59,
  sym_source_file = 60,
  sym__token = 61,
  sym_keyword = 62,
  sym_type_builtin = 63,
  sym_constant_builtin = 64,
  aux_sym_source_file_repeat1 = 65,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_module] = "module",
  [anon_sym_pub] = "pub",
  [anon_sym_import] = "import",
  [anon_sym_imports] = "imports",
  [anon_sym_as] = "as",
  [anon_sym_apply] = "apply",
  [anon_sym_return] = "return",
  [anon_sym_end] = "end",
  [anon_sym_if] = "if",
  [anon_sym_elif] = "elif",
  [anon_sym_else] = "else",
  [anon_sym_while] = "while",
  [anon_sym_for] = "for",
  [anon_sym_in] = "in",
  [anon_sym_of] = "of",
  [anon_sym_by] = "by",
  [anon_sym_repeat] = "repeat",
  [anon_sym_times] = "times",
  [anon_sym_break] = "break",
  [anon_sym_continue] = "continue",
  [anon_sym_match] = "match",
  [anon_sym_case] = "case",
  [anon_sym_loop] = "loop",
  [anon_sym_struct] = "struct",
  [anon_sym_enum] = "enum",
  [anon_sym_alias] = "alias",
  [anon_sym_do] = "do",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [anon_sym_not] = "not",
  [anon_sym_using] = "using",
  [anon_sym_try] = "try",
  [anon_sym_const] = "const",
  [anon_sym_var] = "var",
  [anon_sym_int] = "int",
  [anon_sym_float] = "float",
  [anon_sym_bool] = "bool",
  [anon_sym_string] = "string",
  [anon_sym_bytes] = "bytes",
  [anon_sym_void] = "void",
  [anon_sym_decimal] = "decimal",
  [anon_sym_list] = "list",
  [anon_sym_map] = "map",
  [anon_sym_optional] = "optional",
  [anon_sym_result] = "result",
  [anon_sym_range] = "range",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_none] = "none",
  [anon_sym_success] = "success",
  [anon_sym_error] = "error",
  [anon_sym_some] = "some",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_operator] = "operator",
  [sym_punctuation] = "punctuation",
  [sym_block_comment] = "block_comment",
  [sym_line_comment] = "line_comment",
  [sym_source_file] = "source_file",
  [sym__token] = "_token",
  [sym_keyword] = "keyword",
  [sym_type_builtin] = "type_builtin",
  [sym_constant_builtin] = "constant_builtin",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_pub] = anon_sym_pub,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_imports] = anon_sym_imports,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_apply] = anon_sym_apply,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_elif] = anon_sym_elif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_of] = anon_sym_of,
  [anon_sym_by] = anon_sym_by,
  [anon_sym_repeat] = anon_sym_repeat,
  [anon_sym_times] = anon_sym_times,
  [anon_sym_break] = anon_sym_break,
  [anon_sym_continue] = anon_sym_continue,
  [anon_sym_match] = anon_sym_match,
  [anon_sym_case] = anon_sym_case,
  [anon_sym_loop] = anon_sym_loop,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_alias] = anon_sym_alias,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_using] = anon_sym_using,
  [anon_sym_try] = anon_sym_try,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_bytes] = anon_sym_bytes,
  [anon_sym_void] = anon_sym_void,
  [anon_sym_decimal] = anon_sym_decimal,
  [anon_sym_list] = anon_sym_list,
  [anon_sym_map] = anon_sym_map,
  [anon_sym_optional] = anon_sym_optional,
  [anon_sym_result] = anon_sym_result,
  [anon_sym_range] = anon_sym_range,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_none] = anon_sym_none,
  [anon_sym_success] = anon_sym_success,
  [anon_sym_error] = anon_sym_error,
  [anon_sym_some] = anon_sym_some,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_operator] = sym_operator,
  [sym_punctuation] = sym_punctuation,
  [sym_block_comment] = sym_block_comment,
  [sym_line_comment] = sym_line_comment,
  [sym_source_file] = sym_source_file,
  [sym__token] = sym__token,
  [sym_keyword] = sym_keyword,
  [sym_type_builtin] = sym_type_builtin,
  [sym_constant_builtin] = sym_constant_builtin,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pub] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_imports] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_apply] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_of] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_by] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_repeat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_times] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_break] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_continue] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_match] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_case] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_loop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_alias] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_using] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_try] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bytes] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_void] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_decimal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_list] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_map] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_optional] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_result] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_range] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_none] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_success] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_error] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_some] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__token] = {
    .visible = false,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_type_builtin] = {
    .visible = true,
    .named = true,
  },
  [sym_constant_builtin] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      ADVANCE_MAP(
        '!', 12,
        '"', 2,
        '*', 37,
        '+', 37,
        '-', 36,
        '.', 40,
        '/', 37,
        '0', 24,
        '<', 37,
        '=', 38,
        '>', 37,
        'b', 42,
        'f', 41,
        '%', 35,
        '?', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('(' <= lookahead && lookahead <= ',') ||
          lookahead == ':' ||
          lookahead == ';' ||
          lookahead == '[' ||
          lookahead == ']' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(39);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '}') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(21);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead == '{') ADVANCE(6);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(31);
      if (lookahead == '\\') ADVANCE(21);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(31);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead == '{') ADVANCE(6);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead == '{') ADVANCE(6);
      if (lookahead == '}') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(33);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(7);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '"') ADVANCE(8);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(44);
      if (lookahead == '|') ADVANCE(11);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == '-') ADVANCE(10);
      if (lookahead == '|') ADVANCE(11);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == '=') ADVANCE(35);
      END_STATE();
    case 13:
      if (lookahead == '|') ADVANCE(11);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == '}') ADVANCE(5);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 15:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 16:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(27);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(28);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(30);
      END_STATE();
    case 21:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 22:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_number);
      ADVANCE_MAP(
        '.', 18,
        'B', 16,
        'b', 16,
        'E', 15,
        'e', 15,
        'O', 17,
        'o', 17,
        'X', 20,
        'x', 20,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '7') ||
          lookahead == '_') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(9);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(33);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '}') ADVANCE(5);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_operator);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '-') ADVANCE(45);
      if (lookahead == '=' ||
          lookahead == '>') ADVANCE(35);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '=') ADVANCE(35);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '=' ||
          lookahead == '>') ADVANCE(35);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_punctuation);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_punctuation);
      if (lookahead == '.') ADVANCE(35);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '"') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '"') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_block_comment);
      if (lookahead == '|') ADVANCE(11);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '|') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'e', 5,
        'f', 6,
        'i', 7,
        'l', 8,
        'm', 9,
        'n', 10,
        'o', 11,
        'p', 12,
        'r', 13,
        's', 14,
        't', 15,
        'u', 16,
        'v', 17,
        'w', 18,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(19);
      if (lookahead == 'n') ADVANCE(20);
      if (lookahead == 'p') ADVANCE(21);
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(23);
      if (lookahead == 'r') ADVANCE(24);
      if (lookahead == 'y') ADVANCE(25);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(26);
      if (lookahead == 'o') ADVANCE(27);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(28);
      if (lookahead == 'o') ADVANCE(29);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(30);
      if (lookahead == 'n') ADVANCE(31);
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(33);
      if (lookahead == 'l') ADVANCE(34);
      if (lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 7:
      if (lookahead == 'f') ADVANCE(36);
      if (lookahead == 'm') ADVANCE(37);
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 8:
      if (lookahead == 'i') ADVANCE(39);
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(41);
      if (lookahead == 'o') ADVANCE(42);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(43);
      END_STATE();
    case 11:
      if (lookahead == 'f') ADVANCE(44);
      if (lookahead == 'p') ADVANCE(45);
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 12:
      if (lookahead == 'u') ADVANCE(47);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(48);
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 14:
      if (lookahead == 'o') ADVANCE(50);
      if (lookahead == 't') ADVANCE(51);
      if (lookahead == 'u') ADVANCE(52);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(53);
      if (lookahead == 'r') ADVANCE(54);
      END_STATE();
    case 16:
      if (lookahead == 's') ADVANCE(55);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(56);
      if (lookahead == 'o') ADVANCE(57);
      END_STATE();
    case 18:
      if (lookahead == 'h') ADVANCE(58);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(59);
      END_STATE();
    case 20:
      if (lookahead == 'd') ADVANCE(60);
      END_STATE();
    case 21:
      if (lookahead == 'p') ADVANCE(61);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(62);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_by);
      if (lookahead == 't') ADVANCE(64);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(65);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(66);
      END_STATE();
    case 28:
      if (lookahead == 'c') ADVANCE(67);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(68);
      if (lookahead == 's') ADVANCE(69);
      END_STATE();
    case 31:
      if (lookahead == 'd') ADVANCE(70);
      if (lookahead == 'u') ADVANCE(71);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(72);
      END_STATE();
    case 33:
      if (lookahead == 'l') ADVANCE(73);
      END_STATE();
    case 34:
      if (lookahead == 'o') ADVANCE(74);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(75);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 37:
      if (lookahead == 'p') ADVANCE(76);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead == 't') ADVANCE(77);
      END_STATE();
    case 39:
      if (lookahead == 's') ADVANCE(78);
      END_STATE();
    case 40:
      if (lookahead == 'o') ADVANCE(79);
      END_STATE();
    case 41:
      if (lookahead == 'p') ADVANCE(80);
      if (lookahead == 't') ADVANCE(81);
      END_STATE();
    case 42:
      if (lookahead == 'd') ADVANCE(82);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(83);
      if (lookahead == 't') ADVANCE(84);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_of);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(85);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 47:
      if (lookahead == 'b') ADVANCE(86);
      END_STATE();
    case 48:
      if (lookahead == 'n') ADVANCE(87);
      END_STATE();
    case 49:
      if (lookahead == 'p') ADVANCE(88);
      if (lookahead == 's') ADVANCE(89);
      if (lookahead == 't') ADVANCE(90);
      END_STATE();
    case 50:
      if (lookahead == 'm') ADVANCE(91);
      END_STATE();
    case 51:
      if (lookahead == 'r') ADVANCE(92);
      END_STATE();
    case 52:
      if (lookahead == 'c') ADVANCE(93);
      END_STATE();
    case 53:
      if (lookahead == 'm') ADVANCE(94);
      END_STATE();
    case 54:
      if (lookahead == 'u') ADVANCE(95);
      if (lookahead == 'y') ADVANCE(96);
      END_STATE();
    case 55:
      if (lookahead == 'i') ADVANCE(97);
      END_STATE();
    case 56:
      if (lookahead == 'r') ADVANCE(98);
      END_STATE();
    case 57:
      if (lookahead == 'i') ADVANCE(99);
      END_STATE();
    case 58:
      if (lookahead == 'i') ADVANCE(100);
      END_STATE();
    case 59:
      if (lookahead == 'a') ADVANCE(101);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 61:
      if (lookahead == 'l') ADVANCE(102);
      END_STATE();
    case 62:
      if (lookahead == 'l') ADVANCE(103);
      END_STATE();
    case 63:
      if (lookahead == 'a') ADVANCE(104);
      END_STATE();
    case 64:
      if (lookahead == 'e') ADVANCE(105);
      END_STATE();
    case 65:
      if (lookahead == 'e') ADVANCE(106);
      END_STATE();
    case 66:
      if (lookahead == 's') ADVANCE(107);
      if (lookahead == 't') ADVANCE(108);
      END_STATE();
    case 67:
      if (lookahead == 'i') ADVANCE(109);
      END_STATE();
    case 68:
      if (lookahead == 'f') ADVANCE(110);
      END_STATE();
    case 69:
      if (lookahead == 'e') ADVANCE(111);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 71:
      if (lookahead == 'm') ADVANCE(112);
      END_STATE();
    case 72:
      if (lookahead == 'o') ADVANCE(113);
      END_STATE();
    case 73:
      if (lookahead == 's') ADVANCE(114);
      END_STATE();
    case 74:
      if (lookahead == 'a') ADVANCE(115);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 76:
      if (lookahead == 'o') ADVANCE(116);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 78:
      if (lookahead == 't') ADVANCE(117);
      END_STATE();
    case 79:
      if (lookahead == 'p') ADVANCE(118);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_map);
      END_STATE();
    case 81:
      if (lookahead == 'c') ADVANCE(119);
      END_STATE();
    case 82:
      if (lookahead == 'u') ADVANCE(120);
      END_STATE();
    case 83:
      if (lookahead == 'e') ADVANCE(121);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 85:
      if (lookahead == 'i') ADVANCE(122);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_pub);
      END_STATE();
    case 87:
      if (lookahead == 'g') ADVANCE(123);
      END_STATE();
    case 88:
      if (lookahead == 'e') ADVANCE(124);
      END_STATE();
    case 89:
      if (lookahead == 'u') ADVANCE(125);
      END_STATE();
    case 90:
      if (lookahead == 'u') ADVANCE(126);
      END_STATE();
    case 91:
      if (lookahead == 'e') ADVANCE(127);
      END_STATE();
    case 92:
      if (lookahead == 'i') ADVANCE(128);
      if (lookahead == 'u') ADVANCE(129);
      END_STATE();
    case 93:
      if (lookahead == 'c') ADVANCE(130);
      END_STATE();
    case 94:
      if (lookahead == 'e') ADVANCE(131);
      END_STATE();
    case 95:
      if (lookahead == 'e') ADVANCE(132);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_try);
      END_STATE();
    case 97:
      if (lookahead == 'n') ADVANCE(133);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 99:
      if (lookahead == 'd') ADVANCE(134);
      END_STATE();
    case 100:
      if (lookahead == 'l') ADVANCE(135);
      END_STATE();
    case 101:
      if (lookahead == 's') ADVANCE(136);
      END_STATE();
    case 102:
      if (lookahead == 'y') ADVANCE(137);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 104:
      if (lookahead == 'k') ADVANCE(138);
      END_STATE();
    case 105:
      if (lookahead == 's') ADVANCE(139);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_case);
      END_STATE();
    case 107:
      if (lookahead == 't') ADVANCE(140);
      END_STATE();
    case 108:
      if (lookahead == 'i') ADVANCE(141);
      END_STATE();
    case 109:
      if (lookahead == 'm') ADVANCE(142);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_elif);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 113:
      if (lookahead == 'r') ADVANCE(143);
      END_STATE();
    case 114:
      if (lookahead == 'e') ADVANCE(144);
      END_STATE();
    case 115:
      if (lookahead == 't') ADVANCE(145);
      END_STATE();
    case 116:
      if (lookahead == 'r') ADVANCE(146);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_list);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_loop);
      END_STATE();
    case 119:
      if (lookahead == 'h') ADVANCE(147);
      END_STATE();
    case 120:
      if (lookahead == 'l') ADVANCE(148);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_none);
      END_STATE();
    case 122:
      if (lookahead == 'o') ADVANCE(149);
      END_STATE();
    case 123:
      if (lookahead == 'e') ADVANCE(150);
      END_STATE();
    case 124:
      if (lookahead == 'a') ADVANCE(151);
      END_STATE();
    case 125:
      if (lookahead == 'l') ADVANCE(152);
      END_STATE();
    case 126:
      if (lookahead == 'r') ADVANCE(153);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_some);
      END_STATE();
    case 128:
      if (lookahead == 'n') ADVANCE(154);
      END_STATE();
    case 129:
      if (lookahead == 'c') ADVANCE(155);
      END_STATE();
    case 130:
      if (lookahead == 'e') ADVANCE(156);
      END_STATE();
    case 131:
      if (lookahead == 's') ADVANCE(157);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 133:
      if (lookahead == 'g') ADVANCE(158);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(anon_sym_void);
      END_STATE();
    case 135:
      if (lookahead == 'e') ADVANCE(159);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(anon_sym_alias);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(anon_sym_apply);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(anon_sym_break);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(anon_sym_bytes);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 141:
      if (lookahead == 'n') ADVANCE(160);
      END_STATE();
    case 142:
      if (lookahead == 'a') ADVANCE(161);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(anon_sym_error);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(anon_sym_float);
      END_STATE();
    case 146:
      if (lookahead == 't') ADVANCE(162);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(anon_sym_match);
      END_STATE();
    case 148:
      if (lookahead == 'e') ADVANCE(163);
      END_STATE();
    case 149:
      if (lookahead == 'n') ADVANCE(164);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(anon_sym_range);
      END_STATE();
    case 151:
      if (lookahead == 't') ADVANCE(165);
      END_STATE();
    case 152:
      if (lookahead == 't') ADVANCE(166);
      END_STATE();
    case 153:
      if (lookahead == 'n') ADVANCE(167);
      END_STATE();
    case 154:
      if (lookahead == 'g') ADVANCE(168);
      END_STATE();
    case 155:
      if (lookahead == 't') ADVANCE(169);
      END_STATE();
    case 156:
      if (lookahead == 's') ADVANCE(170);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(anon_sym_times);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(anon_sym_using);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 160:
      if (lookahead == 'u') ADVANCE(171);
      END_STATE();
    case 161:
      if (lookahead == 'l') ADVANCE(172);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(anon_sym_import);
      if (lookahead == 's') ADVANCE(173);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 164:
      if (lookahead == 'a') ADVANCE(174);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(anon_sym_repeat);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(anon_sym_result);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 170:
      if (lookahead == 's') ADVANCE(175);
      END_STATE();
    case 171:
      if (lookahead == 'e') ADVANCE(176);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(anon_sym_decimal);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(anon_sym_imports);
      END_STATE();
    case 174:
      if (lookahead == 'l') ADVANCE(177);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(anon_sym_success);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(anon_sym_continue);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(anon_sym_optional);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [anon_sym_pub] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_imports] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_apply] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_elif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_of] = ACTIONS(1),
    [anon_sym_by] = ACTIONS(1),
    [anon_sym_repeat] = ACTIONS(1),
    [anon_sym_times] = ACTIONS(1),
    [anon_sym_break] = ACTIONS(1),
    [anon_sym_continue] = ACTIONS(1),
    [anon_sym_match] = ACTIONS(1),
    [anon_sym_case] = ACTIONS(1),
    [anon_sym_loop] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_alias] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_using] = ACTIONS(1),
    [anon_sym_try] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_bytes] = ACTIONS(1),
    [anon_sym_void] = ACTIONS(1),
    [anon_sym_decimal] = ACTIONS(1),
    [anon_sym_list] = ACTIONS(1),
    [anon_sym_map] = ACTIONS(1),
    [anon_sym_optional] = ACTIONS(1),
    [anon_sym_result] = ACTIONS(1),
    [anon_sym_range] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_none] = ACTIONS(1),
    [anon_sym_success] = ACTIONS(1),
    [anon_sym_error] = ACTIONS(1),
    [anon_sym_some] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_operator] = ACTIONS(1),
    [sym_punctuation] = ACTIONS(1),
    [sym_block_comment] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(5),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(7),
    [sym__token] = STATE(2),
    [sym_keyword] = STATE(2),
    [sym_type_builtin] = STATE(2),
    [sym_constant_builtin] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_module] = ACTIONS(11),
    [anon_sym_pub] = ACTIONS(11),
    [anon_sym_import] = ACTIONS(11),
    [anon_sym_imports] = ACTIONS(11),
    [anon_sym_as] = ACTIONS(11),
    [anon_sym_apply] = ACTIONS(11),
    [anon_sym_return] = ACTIONS(11),
    [anon_sym_end] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_elif] = ACTIONS(11),
    [anon_sym_else] = ACTIONS(11),
    [anon_sym_while] = ACTIONS(11),
    [anon_sym_for] = ACTIONS(11),
    [anon_sym_in] = ACTIONS(11),
    [anon_sym_of] = ACTIONS(11),
    [anon_sym_by] = ACTIONS(11),
    [anon_sym_repeat] = ACTIONS(11),
    [anon_sym_times] = ACTIONS(11),
    [anon_sym_break] = ACTIONS(11),
    [anon_sym_continue] = ACTIONS(11),
    [anon_sym_match] = ACTIONS(11),
    [anon_sym_case] = ACTIONS(11),
    [anon_sym_loop] = ACTIONS(11),
    [anon_sym_struct] = ACTIONS(11),
    [anon_sym_enum] = ACTIONS(11),
    [anon_sym_alias] = ACTIONS(11),
    [anon_sym_do] = ACTIONS(11),
    [anon_sym_and] = ACTIONS(11),
    [anon_sym_or] = ACTIONS(11),
    [anon_sym_not] = ACTIONS(11),
    [anon_sym_using] = ACTIONS(11),
    [anon_sym_try] = ACTIONS(11),
    [anon_sym_const] = ACTIONS(11),
    [anon_sym_var] = ACTIONS(11),
    [anon_sym_int] = ACTIONS(13),
    [anon_sym_float] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [anon_sym_string] = ACTIONS(13),
    [anon_sym_bytes] = ACTIONS(13),
    [anon_sym_void] = ACTIONS(13),
    [anon_sym_decimal] = ACTIONS(13),
    [anon_sym_list] = ACTIONS(13),
    [anon_sym_map] = ACTIONS(13),
    [anon_sym_optional] = ACTIONS(13),
    [anon_sym_result] = ACTIONS(13),
    [anon_sym_range] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [anon_sym_none] = ACTIONS(15),
    [anon_sym_success] = ACTIONS(15),
    [anon_sym_error] = ACTIONS(15),
    [anon_sym_some] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [sym_operator] = ACTIONS(9),
    [sym_punctuation] = ACTIONS(9),
    [sym_block_comment] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym__token] = STATE(3),
    [sym_keyword] = STATE(3),
    [sym_type_builtin] = STATE(3),
    [sym_constant_builtin] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [anon_sym_module] = ACTIONS(11),
    [anon_sym_pub] = ACTIONS(11),
    [anon_sym_import] = ACTIONS(11),
    [anon_sym_imports] = ACTIONS(11),
    [anon_sym_as] = ACTIONS(11),
    [anon_sym_apply] = ACTIONS(11),
    [anon_sym_return] = ACTIONS(11),
    [anon_sym_end] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_elif] = ACTIONS(11),
    [anon_sym_else] = ACTIONS(11),
    [anon_sym_while] = ACTIONS(11),
    [anon_sym_for] = ACTIONS(11),
    [anon_sym_in] = ACTIONS(11),
    [anon_sym_of] = ACTIONS(11),
    [anon_sym_by] = ACTIONS(11),
    [anon_sym_repeat] = ACTIONS(11),
    [anon_sym_times] = ACTIONS(11),
    [anon_sym_break] = ACTIONS(11),
    [anon_sym_continue] = ACTIONS(11),
    [anon_sym_match] = ACTIONS(11),
    [anon_sym_case] = ACTIONS(11),
    [anon_sym_loop] = ACTIONS(11),
    [anon_sym_struct] = ACTIONS(11),
    [anon_sym_enum] = ACTIONS(11),
    [anon_sym_alias] = ACTIONS(11),
    [anon_sym_do] = ACTIONS(11),
    [anon_sym_and] = ACTIONS(11),
    [anon_sym_or] = ACTIONS(11),
    [anon_sym_not] = ACTIONS(11),
    [anon_sym_using] = ACTIONS(11),
    [anon_sym_try] = ACTIONS(11),
    [anon_sym_const] = ACTIONS(11),
    [anon_sym_var] = ACTIONS(11),
    [anon_sym_int] = ACTIONS(13),
    [anon_sym_float] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [anon_sym_string] = ACTIONS(13),
    [anon_sym_bytes] = ACTIONS(13),
    [anon_sym_void] = ACTIONS(13),
    [anon_sym_decimal] = ACTIONS(13),
    [anon_sym_list] = ACTIONS(13),
    [anon_sym_map] = ACTIONS(13),
    [anon_sym_optional] = ACTIONS(13),
    [anon_sym_result] = ACTIONS(13),
    [anon_sym_range] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [anon_sym_none] = ACTIONS(15),
    [anon_sym_success] = ACTIONS(15),
    [anon_sym_error] = ACTIONS(15),
    [anon_sym_some] = ACTIONS(15),
    [sym_number] = ACTIONS(23),
    [sym_string] = ACTIONS(23),
    [sym_operator] = ACTIONS(21),
    [sym_punctuation] = ACTIONS(21),
    [sym_block_comment] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(5),
  },
  [STATE(3)] = {
    [sym__token] = STATE(3),
    [sym_keyword] = STATE(3),
    [sym_type_builtin] = STATE(3),
    [sym_constant_builtin] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_identifier] = ACTIONS(27),
    [anon_sym_module] = ACTIONS(30),
    [anon_sym_pub] = ACTIONS(30),
    [anon_sym_import] = ACTIONS(30),
    [anon_sym_imports] = ACTIONS(30),
    [anon_sym_as] = ACTIONS(30),
    [anon_sym_apply] = ACTIONS(30),
    [anon_sym_return] = ACTIONS(30),
    [anon_sym_end] = ACTIONS(30),
    [anon_sym_if] = ACTIONS(30),
    [anon_sym_elif] = ACTIONS(30),
    [anon_sym_else] = ACTIONS(30),
    [anon_sym_while] = ACTIONS(30),
    [anon_sym_for] = ACTIONS(30),
    [anon_sym_in] = ACTIONS(30),
    [anon_sym_of] = ACTIONS(30),
    [anon_sym_by] = ACTIONS(30),
    [anon_sym_repeat] = ACTIONS(30),
    [anon_sym_times] = ACTIONS(30),
    [anon_sym_break] = ACTIONS(30),
    [anon_sym_continue] = ACTIONS(30),
    [anon_sym_match] = ACTIONS(30),
    [anon_sym_case] = ACTIONS(30),
    [anon_sym_loop] = ACTIONS(30),
    [anon_sym_struct] = ACTIONS(30),
    [anon_sym_enum] = ACTIONS(30),
    [anon_sym_alias] = ACTIONS(30),
    [anon_sym_do] = ACTIONS(30),
    [anon_sym_and] = ACTIONS(30),
    [anon_sym_or] = ACTIONS(30),
    [anon_sym_not] = ACTIONS(30),
    [anon_sym_using] = ACTIONS(30),
    [anon_sym_try] = ACTIONS(30),
    [anon_sym_const] = ACTIONS(30),
    [anon_sym_var] = ACTIONS(30),
    [anon_sym_int] = ACTIONS(33),
    [anon_sym_float] = ACTIONS(33),
    [anon_sym_bool] = ACTIONS(33),
    [anon_sym_string] = ACTIONS(33),
    [anon_sym_bytes] = ACTIONS(33),
    [anon_sym_void] = ACTIONS(33),
    [anon_sym_decimal] = ACTIONS(33),
    [anon_sym_list] = ACTIONS(33),
    [anon_sym_map] = ACTIONS(33),
    [anon_sym_optional] = ACTIONS(33),
    [anon_sym_result] = ACTIONS(33),
    [anon_sym_range] = ACTIONS(33),
    [anon_sym_true] = ACTIONS(36),
    [anon_sym_false] = ACTIONS(36),
    [anon_sym_none] = ACTIONS(36),
    [anon_sym_success] = ACTIONS(36),
    [anon_sym_error] = ACTIONS(36),
    [anon_sym_some] = ACTIONS(36),
    [sym_number] = ACTIONS(39),
    [sym_string] = ACTIONS(39),
    [sym_operator] = ACTIONS(27),
    [sym_punctuation] = ACTIONS(27),
    [sym_block_comment] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(5),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(42),
    [sym_identifier] = ACTIONS(44),
    [anon_sym_module] = ACTIONS(44),
    [anon_sym_pub] = ACTIONS(44),
    [anon_sym_import] = ACTIONS(44),
    [anon_sym_imports] = ACTIONS(44),
    [anon_sym_as] = ACTIONS(44),
    [anon_sym_apply] = ACTIONS(44),
    [anon_sym_return] = ACTIONS(44),
    [anon_sym_end] = ACTIONS(44),
    [anon_sym_if] = ACTIONS(44),
    [anon_sym_elif] = ACTIONS(44),
    [anon_sym_else] = ACTIONS(44),
    [anon_sym_while] = ACTIONS(44),
    [anon_sym_for] = ACTIONS(44),
    [anon_sym_in] = ACTIONS(44),
    [anon_sym_of] = ACTIONS(44),
    [anon_sym_by] = ACTIONS(44),
    [anon_sym_repeat] = ACTIONS(44),
    [anon_sym_times] = ACTIONS(44),
    [anon_sym_break] = ACTIONS(44),
    [anon_sym_continue] = ACTIONS(44),
    [anon_sym_match] = ACTIONS(44),
    [anon_sym_case] = ACTIONS(44),
    [anon_sym_loop] = ACTIONS(44),
    [anon_sym_struct] = ACTIONS(44),
    [anon_sym_enum] = ACTIONS(44),
    [anon_sym_alias] = ACTIONS(44),
    [anon_sym_do] = ACTIONS(44),
    [anon_sym_and] = ACTIONS(44),
    [anon_sym_or] = ACTIONS(44),
    [anon_sym_not] = ACTIONS(44),
    [anon_sym_using] = ACTIONS(44),
    [anon_sym_try] = ACTIONS(44),
    [anon_sym_const] = ACTIONS(44),
    [anon_sym_var] = ACTIONS(44),
    [anon_sym_int] = ACTIONS(44),
    [anon_sym_float] = ACTIONS(44),
    [anon_sym_bool] = ACTIONS(44),
    [anon_sym_string] = ACTIONS(44),
    [anon_sym_bytes] = ACTIONS(44),
    [anon_sym_void] = ACTIONS(44),
    [anon_sym_decimal] = ACTIONS(44),
    [anon_sym_list] = ACTIONS(44),
    [anon_sym_map] = ACTIONS(44),
    [anon_sym_optional] = ACTIONS(44),
    [anon_sym_result] = ACTIONS(44),
    [anon_sym_range] = ACTIONS(44),
    [anon_sym_true] = ACTIONS(44),
    [anon_sym_false] = ACTIONS(44),
    [anon_sym_none] = ACTIONS(44),
    [anon_sym_success] = ACTIONS(44),
    [anon_sym_error] = ACTIONS(44),
    [anon_sym_some] = ACTIONS(44),
    [sym_number] = ACTIONS(42),
    [sym_string] = ACTIONS(42),
    [sym_operator] = ACTIONS(44),
    [sym_punctuation] = ACTIONS(44),
    [sym_block_comment] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(5),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(46),
    [sym_identifier] = ACTIONS(48),
    [anon_sym_module] = ACTIONS(48),
    [anon_sym_pub] = ACTIONS(48),
    [anon_sym_import] = ACTIONS(48),
    [anon_sym_imports] = ACTIONS(48),
    [anon_sym_as] = ACTIONS(48),
    [anon_sym_apply] = ACTIONS(48),
    [anon_sym_return] = ACTIONS(48),
    [anon_sym_end] = ACTIONS(48),
    [anon_sym_if] = ACTIONS(48),
    [anon_sym_elif] = ACTIONS(48),
    [anon_sym_else] = ACTIONS(48),
    [anon_sym_while] = ACTIONS(48),
    [anon_sym_for] = ACTIONS(48),
    [anon_sym_in] = ACTIONS(48),
    [anon_sym_of] = ACTIONS(48),
    [anon_sym_by] = ACTIONS(48),
    [anon_sym_repeat] = ACTIONS(48),
    [anon_sym_times] = ACTIONS(48),
    [anon_sym_break] = ACTIONS(48),
    [anon_sym_continue] = ACTIONS(48),
    [anon_sym_match] = ACTIONS(48),
    [anon_sym_case] = ACTIONS(48),
    [anon_sym_loop] = ACTIONS(48),
    [anon_sym_struct] = ACTIONS(48),
    [anon_sym_enum] = ACTIONS(48),
    [anon_sym_alias] = ACTIONS(48),
    [anon_sym_do] = ACTIONS(48),
    [anon_sym_and] = ACTIONS(48),
    [anon_sym_or] = ACTIONS(48),
    [anon_sym_not] = ACTIONS(48),
    [anon_sym_using] = ACTIONS(48),
    [anon_sym_try] = ACTIONS(48),
    [anon_sym_const] = ACTIONS(48),
    [anon_sym_var] = ACTIONS(48),
    [anon_sym_int] = ACTIONS(48),
    [anon_sym_float] = ACTIONS(48),
    [anon_sym_bool] = ACTIONS(48),
    [anon_sym_string] = ACTIONS(48),
    [anon_sym_bytes] = ACTIONS(48),
    [anon_sym_void] = ACTIONS(48),
    [anon_sym_decimal] = ACTIONS(48),
    [anon_sym_list] = ACTIONS(48),
    [anon_sym_map] = ACTIONS(48),
    [anon_sym_optional] = ACTIONS(48),
    [anon_sym_result] = ACTIONS(48),
    [anon_sym_range] = ACTIONS(48),
    [anon_sym_true] = ACTIONS(48),
    [anon_sym_false] = ACTIONS(48),
    [anon_sym_none] = ACTIONS(48),
    [anon_sym_success] = ACTIONS(48),
    [anon_sym_error] = ACTIONS(48),
    [anon_sym_some] = ACTIONS(48),
    [sym_number] = ACTIONS(46),
    [sym_string] = ACTIONS(46),
    [sym_operator] = ACTIONS(48),
    [sym_punctuation] = ACTIONS(48),
    [sym_block_comment] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(5),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(50),
    [sym_identifier] = ACTIONS(52),
    [anon_sym_module] = ACTIONS(52),
    [anon_sym_pub] = ACTIONS(52),
    [anon_sym_import] = ACTIONS(52),
    [anon_sym_imports] = ACTIONS(52),
    [anon_sym_as] = ACTIONS(52),
    [anon_sym_apply] = ACTIONS(52),
    [anon_sym_return] = ACTIONS(52),
    [anon_sym_end] = ACTIONS(52),
    [anon_sym_if] = ACTIONS(52),
    [anon_sym_elif] = ACTIONS(52),
    [anon_sym_else] = ACTIONS(52),
    [anon_sym_while] = ACTIONS(52),
    [anon_sym_for] = ACTIONS(52),
    [anon_sym_in] = ACTIONS(52),
    [anon_sym_of] = ACTIONS(52),
    [anon_sym_by] = ACTIONS(52),
    [anon_sym_repeat] = ACTIONS(52),
    [anon_sym_times] = ACTIONS(52),
    [anon_sym_break] = ACTIONS(52),
    [anon_sym_continue] = ACTIONS(52),
    [anon_sym_match] = ACTIONS(52),
    [anon_sym_case] = ACTIONS(52),
    [anon_sym_loop] = ACTIONS(52),
    [anon_sym_struct] = ACTIONS(52),
    [anon_sym_enum] = ACTIONS(52),
    [anon_sym_alias] = ACTIONS(52),
    [anon_sym_do] = ACTIONS(52),
    [anon_sym_and] = ACTIONS(52),
    [anon_sym_or] = ACTIONS(52),
    [anon_sym_not] = ACTIONS(52),
    [anon_sym_using] = ACTIONS(52),
    [anon_sym_try] = ACTIONS(52),
    [anon_sym_const] = ACTIONS(52),
    [anon_sym_var] = ACTIONS(52),
    [anon_sym_int] = ACTIONS(52),
    [anon_sym_float] = ACTIONS(52),
    [anon_sym_bool] = ACTIONS(52),
    [anon_sym_string] = ACTIONS(52),
    [anon_sym_bytes] = ACTIONS(52),
    [anon_sym_void] = ACTIONS(52),
    [anon_sym_decimal] = ACTIONS(52),
    [anon_sym_list] = ACTIONS(52),
    [anon_sym_map] = ACTIONS(52),
    [anon_sym_optional] = ACTIONS(52),
    [anon_sym_result] = ACTIONS(52),
    [anon_sym_range] = ACTIONS(52),
    [anon_sym_true] = ACTIONS(52),
    [anon_sym_false] = ACTIONS(52),
    [anon_sym_none] = ACTIONS(52),
    [anon_sym_success] = ACTIONS(52),
    [anon_sym_error] = ACTIONS(52),
    [anon_sym_some] = ACTIONS(52),
    [sym_number] = ACTIONS(50),
    [sym_string] = ACTIONS(50),
    [sym_operator] = ACTIONS(52),
    [sym_punctuation] = ACTIONS(52),
    [sym_block_comment] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_builtin, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_builtin, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant_builtin, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant_builtin, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_oriscript(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "oriscript",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
